import { useCallback, useEffect, useState } from 'react'
import { SearchX } from 'lucide-react'
import {
  BarList,
  ChartCard,
  ColumnChart,
  DataTable,
  Meter,
  StatTile,
} from '../../components/charts'
import { Alert, Card, PageHeader, Spinner } from '../../components/ui'
import { api } from '../../lib/api'
import { formatCount } from '../../lib/format'

const RANGES = [
  { days: 7, label: 'Last 7 days' },
  { days: 14, label: 'Last 14 days' },
  { days: 30, label: 'Last 30 days' },
  { days: 90, label: 'Last 90 days' },
]

const shortDate = (iso) =>
  new Date(`${iso}T00:00:00`).toLocaleDateString(undefined, { day: 'numeric', month: 'short' })

export default function AdminAnalytics() {
  const [days, setDays] = useState(14)
  const [data, setData] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)

  const load = useCallback(async () => {
    setLoading(true)
    try {
      setData(await api.analytics(days))
      setError(null)
    } catch (err) {
      setError(err.message)
    } finally {
      setLoading(false)
    }
  }, [days])

  useEffect(() => {
    load()
  }, [load])

  const perDay = (data?.questions_per_day || []).map((d) => ({ key: d.date, value: d.count }))
  const totalInRange = perDay.reduce((s, d) => s + d.value, 0)
  const grounded = data?.grounded_vs_fallback?.[0]?.count ?? 0
  const refused = data?.grounded_vs_fallback?.[1]?.count ?? 0
  const answered = grounded + refused

  return (
    <div className="mx-auto max-w-7xl px-4 py-6 sm:px-6 sm:py-8">
      <PageHeader title="Analytics" description="How students use the assistant, and where the documents fall short." />

      {/* One filter row above everything it scopes. */}
      <div className="mb-5 flex flex-wrap gap-2" role="group" aria-label="Date range">
        {RANGES.map((r) => (
          <button
            key={r.days}
            type="button"
            onClick={() => setDays(r.days)}
            aria-pressed={days === r.days}
            className={`rounded-lg border px-3 py-1.5 text-sm transition ${
              days === r.days
                ? 'border-brand-600 bg-brand-600 text-white'
                : 'border-slate-300 bg-white text-slate-700 hover:bg-slate-50 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-300 dark:hover:bg-slate-800'
            }`}
          >
            {r.label}
          </button>
        ))}
      </div>

      {error && (
        <div className="mb-4">
          <Alert>{error}</Alert>
        </div>
      )}

      {!data && loading ? (
        <div className="flex justify-center py-20 text-slate-400">
          <Spinner className="size-6" />
        </div>
      ) : data ? (
        // Refetch keeps the frame: hold the previous render at reduced opacity.
        <div className={`space-y-6 transition-opacity ${loading ? 'opacity-60' : ''}`}>
          <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
            <StatTile label="Questions in range" value={totalInRange} sub={RANGES.find((r) => r.days === days)?.label} />
            <StatTile
              label="Average match score"
              value={data.average_similarity ? `${(data.average_similarity * 100).toFixed(0)}%` : '—'}
              sub="best chunk, grounded answers"
            />
            <StatTile
              label="Average response time"
              value={data.average_latency_ms ? `${(data.average_latency_ms / 1000).toFixed(1)}s` : '—'}
              sub="retrieval + generation"
            />
            <StatTile
              label="Generated by the LLM"
              value={`${(data.llm_answer_rate * 100).toFixed(0)}%`}
              sub="of all answers"
            />
          </div>

          <ChartCard
            title="Questions per day"
            subtitle={`${formatCount(totalInRange)} questions`}
            empty={totalInRange === 0}
            emptyText="No questions asked in this period."
            table={
              <DataTable
                columns={[
                  { key: 'key', label: 'Date', format: shortDate },
                  { key: 'value', label: 'Questions', numeric: true },
                ]}
                rows={perDay}
              />
            }
          >
            <ColumnChart data={perDay} valueLabel="Questions" formatLabel={shortDate} />
          </ChartCard>

          <div className="grid gap-6 lg:grid-cols-2">
            <ChartCard
              title="Most-cited documents"
              subtitle="Times each document was cited in an answer"
              empty={!data.top_documents.length}
              emptyText="No answers have cited a document yet."
              table={
                <DataTable
                  columns={[
                    { key: 'label', label: 'Document' },
                    { key: 'count', label: 'Citations', numeric: true },
                  ]}
                  rows={data.top_documents}
                />
              }
            >
              <BarList data={data.top_documents} unit="citations" />
            </ChartCard>

            <ChartCard
              title="Questions by department"
              subtitle="Grounded answers, by the department of the top source"
              empty={!data.questions_by_department.length}
              emptyText="No grounded answers yet."
              table={
                <DataTable
                  columns={[
                    { key: 'label', label: 'Department' },
                    { key: 'count', label: 'Questions', numeric: true },
                  ]}
                  rows={data.questions_by_department}
                />
              }
            >
              <BarList data={data.questions_by_department} unit="questions" />
            </ChartCard>
          </div>

          <div className="grid gap-6 lg:grid-cols-3">
            <Card className="p-5">
              <h2 className="text-sm font-semibold">Answer coverage</h2>
              <div className="mt-4">
                <Meter
                  label="Answered from documents"
                  value={answered ? grounded / answered : 0}
                  caption={`${grounded} answered · ${refused} not found in documents`}
                />
              </div>
              <div className="mt-6">
                <h3 className="mb-3 text-xs font-medium text-slate-500 dark:text-slate-400">Indexed documents by department</h3>
                {data.documents_by_department.length ? (
                  <BarList data={data.documents_by_department} unit="documents" />
                ) : (
                  <p className="text-sm text-slate-500">No documents indexed.</p>
                )}
              </div>
            </Card>

            <Card className="p-5 lg:col-span-2">
              <div className="flex items-center gap-2">
                <SearchX className="size-4 text-amber-600 dark:text-amber-400" aria-hidden="true" />
                <h2 className="text-sm font-semibold">Recent questions the documents couldn't answer</h2>
              </div>
              <p className="mt-0.5 text-xs text-slate-500 dark:text-slate-400">
                These fell below the similarity threshold. Consider uploading documents that cover them.
              </p>
              {data.recent_unanswered.length === 0 ? (
                <p className="py-10 text-center text-sm text-slate-500">Every recent question found a relevant document.</p>
              ) : (
                <ul className="mt-4 divide-y divide-slate-100 dark:divide-slate-800">
                  {data.recent_unanswered.map((q, i) => (
                    <li key={`${i}-${q}`} className="py-2.5 text-sm text-slate-700 dark:text-slate-300">
                      {q}
                    </li>
                  ))}
                </ul>
              )}
            </Card>
          </div>
        </div>
      ) : null}
    </div>
  )
}
